services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    image: mongo:latest
    hostname: mongo
    ports:
      - "27017:27017"
  frontend:
    build:
      context: ./frontend/my-react-vite-app/
      dockerfile: Dockerfile.frontend
    
    ports:
      - 3000:3000